### ISSUE TITLE
バージョンアップでエリア選択ツールでエラー発生しました。

### ISSUE THREAD

**Issue by hirof1** [JOSM/areaselector#36]

**Comment by hirof1** [comment]
org.openstreetmap.josm.tools.JosmRuntimeException: Fatal: 画像 'cancel.png' の配置に失敗しました。これは深刻な構成の問題です。JOSM は動作停止します。
	at org.openstreetmap.josm.tools.ImageProvider.getResource(ImageProvider.java:706)
	at org.openstreetmap.josm.tools.ImageProvider.get(ImageProvider.java:666)
	at org.openstreetmap.josm.tools.ImageProvider.get(ImageProvider.java:812)
	at org.openstreetmap.josm.gui.ExtendedDialog.setButtonIcons(ExtendedDialog.java:187)
	at org.openstreetmap.josm.plugins.areaselector.AddressDialog.<init>(AddressDialog.java:121)
	at org.openstreetmap.josm.plugins.areaselector.AreaSelectorAction.createArea(AreaSelectorAction.java:260)
	at org.openstreetmap.josm.plugins.areaselector.AreaSelectorAction$1.run(AreaSelectorAction.java:150)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by miurahr** [comment]
V2.5.x でこの問題はなおっているはずです。
The issue might be fixed in v2.5.x
