### ISSUE TITLE
Error open areaselector

### ISSUE THREAD

**Issue by Jes-Lop** [JOSM/areaselector#44]
I get this when try to use areaselector:

{{{
Revision:18118
Build-Date:2021-08-02 19:18:35

Identification: JOSM/1.5 (18118 gl) Mac OS X 10.15.7
OS Build number: Mac OS X 10.15.7 (19H1217)
Memory Usage: 344 MB / 4096 MB (142 MB allocated, but free)
Java version: 16.0.2+7, Azul Systems, Inc., OpenJDK 64-Bit Server VM
Look and Feel: com.apple.laf.AquaLookAndFeel
Screen: Display 69501701 1680×1050 (scaling 1.00×1.00) Display 1952439552 2560×1440 (scaling 1.00×1.00)
Maximum Screen Size: 2560×1440
Best cursor sizes: 16×16→16×16, 32×32→32×32
System property file.encoding: UTF-8
System property sun.jnu.encoding: UTF-8
Locale info: gl_ES
Numbers with default locale: 1234567890 -> 1234567890
VM arguments: [-Djpackage.app-version=18118, --add-exports=java.base/sun.security.action=ALL-UNNAMED, --add-exports=java.desktop/com.apple.eawt=ALL-UNNAMED, --add-exports=java.desktop/com.sun.imageio.plugins.jpeg=ALL-UNNAMED, --add-exports=java.desktop/com.sun.imageio.spi=ALL-UNNAMED, --add-opens=java.base/java.lang=ALL-UNNAMED, --add-opens=java.base/java.nio=ALL-UNNAMED, --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED, --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED, --add-opens=java.desktop/javax.imageio.spi=ALL-UNNAMED, --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED, --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED, -Djpackage.app-path=/Applications/JOSM.app/Contents/MacOS/JOSM]
Dataset consistency test: No problems found

Last errors/warnings:
- 00033.081 E: Unsupported savable layer type: WMSLayer
- 00036.266 E: Handled by bug report queue: java.lang.IllegalAccessError: class boofcv.io.image.ConvertBufferedImage (in unnamed module @0x56c1b85f) cannot access class sun.awt.image.ByteInterleavedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x56c1b85f
- 05746.469 E: Handled by bug report queue: java.lang.IllegalAccessError: class boofcv.io.image.ConvertBufferedImage (in unnamed module @0x56c1b85f) cannot access class sun.awt.image.ByteInterleavedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x56c1b85f
- 05945.409 E: Handled by bug report queue: java.lang.IllegalAccessError: class boofcv.io.image.ConvertBufferedImage (in unnamed module @0x56c1b85f) cannot access class sun.awt.image.ByteInterleavedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x56c1b85f
- 05959.910 E: Handled by bug report queue: java.lang.IllegalAccessError: class boofcv.io.image.ConvertBufferedImage (in unnamed module @0x56c1b85f) cannot access class sun.awt.image.ByteInterleavedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x56c1b85f
- 05982.271 E: Handled by bug report queue: java.lang.IllegalAccessError: class boofcv.io.image.ConvertBufferedImage (in unnamed module @0x56c1b85f) cannot access class sun.awt.image.ByteInterleavedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x56c1b85f
- 05991.618 E: Handled by bug report queue: java.lang.IllegalAccessError: class boofcv.io.image.ConvertBufferedImage (in unnamed module @0x56c1b85f) cannot access class sun.awt.image.ByteInterleavedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x56c1b85f
- 05995.604 E: Handled by bug report queue: java.lang.IllegalAccessError: class boofcv.io.image.ConvertBufferedImage (in unnamed module @0x56c1b85f) cannot access class sun.awt.image.ByteInterleavedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x56c1b85f
- 06117.432 E: Handled by bug report queue: java.lang.IllegalAccessError: class boofcv.io.image.ConvertBufferedImage (in unnamed module @0x56c1b85f) cannot access class sun.awt.image.ByteInterleavedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x56c1b85f

=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (22) of main
java.lang.IllegalAccessError: class boofcv.io.image.ConvertBufferedImage (in unnamed module @0x56c1b85f) cannot access class sun.awt.image.ByteInterleavedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x56c1b85f
	at boofcv.io.image.ConvertBufferedImage.convertFrom(ConvertBufferedImage.java:319)
	at org.openstreetmap.josm.plugins.areaselector.ImageAnalyzer.detectCannyArea(ImageAnalyzer.java:690)
	at org.openstreetmap.josm.plugins.areaselector.ImageAnalyzer.getArea(ImageAnalyzer.java:151)
	at org.openstreetmap.josm.plugins.areaselector.AreaSelectorAction.createArea(AreaSelectorAction.java:197)
	at org.openstreetmap.josm.plugins.areaselector.AreaSelectorAction$1.run(AreaSelectorAction.java:150)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
}}}

Any help would be appreciated

**Comment by tsmock** [comment]
Duplicates https://josm.openstreetmap.de/ticket/21511 and #43 .
