### ISSUE TITLE
Error in JOSM 18360

### ISSUE THREAD

**Issue by ivanrome** [JOSM/areaselector#47]
Hello,

Steps:
1. Show the layer: wms:http://ovc.catastro.meh.es/cartografia/INSPIRE/spadgcwms.aspx?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=BU.Building&STYLES=&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}

2. Ctrl + Alt + A: To activate the areaselector tool
3. Click over a building

Expected: 
- New building is created
- A popup is show asking for address details

Actual:

- New building is created
- An error occurs, 
- No pop-up asking for addres details is shown

Here are the error details

> {{{
> Relative:URL: ^/trunk
> Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
> Last:Changed Date: 2022-01-02 21:24:43 +0100 (Sun, 02 Jan 2022)
> Revision:18360
> Build-Date:2022-01-02 20:26:19
> URL:https://josm.openstreetmap.de/svn/trunk
> 
> Identification: JOSM/1.5 (18360 es) Linux Mint 20.3
> Memory Usage: 299 MB / 1986 MB (7 MB allocated, but free)
> Java version: 11.0.13+8-Ubuntu-0ubuntu1.20.04, Ubuntu, OpenJDK 64-Bit Server VM
> Look and Feel: javax.swing.plaf.metal.MetalLookAndFeel
> Screen: :0.0 1920×1080 (scaling 1.00×1.00)
> Maximum Screen Size: 1920×1080
> Best cursor sizes: 16×16→16×16, 32×32→32×32
> Environment variable LANG: es_ES.UTF-8
> System property file.encoding: UTF-8
> System property sun.jnu.encoding: UTF-8
> Locale info: es_ES
> Numbers with default locale: 1234567890 -> 1234567890
> Desktop environment: X-Cinnamon
> Java package: openjdk-11-jre:amd64-11.0.13+8-0ubuntu1~20.04
> fonts-noto: fonts-noto:-
> Dataset consistency test: No problems found
> 
> Plugins:
> + FixAddresses (35893)
> + OpeningHoursEditor (35893)
> + areaselector (368)
> + austriaaddresshelper (1597341117)
> + ejml (35893)
> + log4j (35893)
> + reverter (35893)
> + tageditor (35893)
> + turnlanes-tagging (v0.0.5)
> + utilsplugin2 (35893)
> 
> Map paint styles:
> - https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1
> - https://josm.openstreetmap.de/josmfile?page=Styles/Enhanced_Lane_and_Road_Attributes&zip=1
> - https://raw.githubusercontent.com/species/josm-preset-traffic_sign_direction/master/direction.mapcss
> + https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_Postcode&zip=1
> - https://josm.openstreetmap.de/josmfile?page=Styles/AddressValidator&zip=1
> - https://josm.openstreetmap.de/josmfile?page=Styles/Cycleways&zip=1
> - https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features&zip=1
> - https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features_ryg&zip=1
> - https://josm.openstreetmap.de/josmfile?page=Styles/Cycleways&zip=1
> - https://josm.openstreetmap.de/josmfile?page=Styles/ParkingLanes&zip=1
> + https://josm.openstreetmap.de/josmfile?page=Styles/Sidewalks&zip=1
> - https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_Streets&zip=1
> 
> Last errors/warnings:
> - 00033.145 E: Invalid setting (Icon missing): org.openstreetmap.josm.plugins.fixAddresses.FixAddressesPreferences
> - 00137.966 E: Handled by bug report queue: java.lang.NoSuchMethodError: 'void org.openstreetmap.josm.gui.tagging.ac.AutoCompletingComboBox.setPossibleAcItems(java.util.Collection)'
> 
> 
> 
> === REPORTED CRASH DATA ===
> BugReportExceptionHandler#handleException:
> No data collected.
> 
> Warning issued by: BugReportExceptionHandler#handleException
> 
> === STACK TRACE ===
> Thread: AWT-EventQueue-0 (19) of main
> java.lang.NoSuchMethodError: 'void org.openstreetmap.josm.gui.tagging.ac.AutoCompletingComboBox.setPossibleAcItems(java.util.Collection)'
> 	at org.openstreetmap.josm.plugins.areaselector.AddressDialog.<init>(AddressDialog.java:129)
> 	at org.openstreetmap.josm.plugins.areaselector.AreaSelectorAction.createArea(AreaSelectorAction.java:260)
> 	at org.openstreetmap.josm.plugins.areaselector.AreaSelectorAction$1.run(AreaSelectorAction.java:150)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> }}}

Thanks

**Comment by tsmock** [comment]
Note: This was fixed in https://github.com/JOSM/areaselector/commit/28efff2dbcd5a77f6896819cf0a0eff1eac5bcf5 .

Someone just needs to do a release.
